### ISSUE TITLE
Upgrade from 2.1 to 2.2 using Deb package doesn't seem to work properly.

### ISSUE THREAD

**Issue by MarkBinner** [vkbo/novelWriter#1645] opened 2023-12-23 13:36 UTC
I downloaded the Deb package for version 2.2 and installed it on top of 2.1. In Help > About the version was still saying 2.1. I uninstalled and did a clean install but got the same result. Running the pip upgrade command from a terminal DID update the version.

**Comment by vkbo** [comment] 2023-12-23 17:27
Are you sure the old version wasn't installed via pip? I have never had an issue upgrading with deb packages myself, but it does get messy if you mix install methods. What does `which novelwriter` return?

**Comment by MarkBinner** [comment] 2023-12-23 17:53
I am reasonably sure but not 100% certain. A deb package would always be my first choice. It seems ok now and I have added the PPA to get automatic updates.
Thanks for your speedy reply which is quite refreshing in these times. 

Mark B

On 23 December 2023, at 17:27, Veronica Berglyd Olsen ***@***.***> wrote:

Are you sure the old version wasn't installed via pip? I have never had an issue upgrading with deb packages myself, but it does get messy if you mix install methods. What does which novelwriter return?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/vkbo/novelWriter/issues/1645#issuecomment-1868336370">https://github.com/vkbo/novelWriter/issues/1645#issuecomment-1868336370</a>", "url": "<a href="https://github.com/vkbo/novelWriter/issues/1645#issuecomment-1868336370">https://github.com/vkbo/novelWriter/issues/1645#issuecomment-1868336370</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by vkbo** [comment] 2023-12-23 18:02
I don't think there's a general issue with the packages, and I always install the deb package as I only have Debian computers. So there may be some local mixup. If you figure out what happened, please let me know.

Since the problem is solved, I'll close this.

**Closed by vkbo** 2023-12-23 18:02 UTC
Labels: installation

**Comment by MarkBinner** [comment] 2023-12-23 18:12
Ok,thanks and...

Merry Christmas.

Mark

On 23 December 2023, at 18:02, Veronica Berglyd Olsen ***@***.***> wrote:

I don't think there's a general issue with the packages, and I always install the deb package as I only have Debian computers. So there may be some local mixup. If you figure out what happened, please let me know.

Since the problem is solved, I'll close this.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/vkbo/novelWriter/issues/1645#issuecomment-1868342274">https://github.com/vkbo/novelWriter/issues/1645#issuecomment-1868342274</a>", "url": "<a href="https://github.com/vkbo/novelWriter/issues/1645#issuecomment-1868342274">https://github.com/vkbo/novelWriter/issues/1645#issuecomment-1868342274</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]
