### ISSUE TITLE
find in files (search & replace)

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1736] opened 2024-03-08 17:14 UTC
"find in files" can be approximated using the "search next file" button, but there are some issues making this feature impractical:
- if "search next file" is active, the search always enters the next file, even if there aren't any occurrences of the search string in the next file. I would expect these files to be skipped, otherwise finding the next instance of a search string gets tedious. There can be a long tail of project notes, archived files or even trashed files to skip over.
- search backwards does not enter previous file, even if "search next file" is active. To go back, I need to open the previous document, scroll to the end, click at the end and search backwards from there.

**Comment by vkbo** [comment] 2024-03-08 22:41
Search next file means exactly that, next, not previous file. You can just open the file where you want to start your search and search from there. In any case, this is a duplicate of ticket #1451, so I'm closing this one.

A global search feature is anyway scheduled to be added in 2.4, although it may be bumped to 2.5. See #894.

**Closed** 2024-03-08 22:42 UTC
Labels: duplicate

**Comment by vkbo** [comment] 2024-03-09 09:04
By the way, the [milestones](https://github.com/vkbo/novelWriter/milestones) show what features are planned for each upcoming release. They're no guarantee, as I sometimes bump them to the next release if there is too much in the one I'm working on, but it's still a good indication where features are in the pipeline.

Global search is pretty high on my list now anyway.

**Comment by awqk** [comment] 2024-03-09 11:11
Sorry about not finding #1451 before opening a new issue. Next time I will look past the 1st page of the search results.

Maybe @HeyMyian's suggestion wouldn't be hard to do. It could serve well as a stop-gap measure until global search is implemented, especially if #894 gets delayed again.

**Comment by vkbo** [comment] 2024-03-09 11:21
> Sorry about not finding #1451 before opening a new issue. Next time I will look past the 1st page of the search results.

No worries, it happens.

> Maybe @HeyMyian's suggestion wouldn't be hard to do. It could serve well as a stop-gap measure until global search is implemented, especially if #894 gets delayed again.

I don't really get why it matters that it cannot search backwards as you can just select another search start point. The way the next file feature is implemented is pretty basic. All it does is open the next document when there are no more searches in the current document.

The search implementation itself just hooks into Qt's `find()` call on the text inside the document, and is not implemented outside of the editor. Hence the app itself has no idea if a search result is in a document until it has been opened and searched by the editor itself. This is why documents without search results are not skipped. It is simply not known prior to opening.

I'd rather not waste time developing a new and more flexible next/prev document search when a global search will replace the whole feature. I will probably just remove it when #894 is completed.
