### ISSUE TITLE
[false positive] Installer quarantined as malware by Windows Defender

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1766] opened 2024-03-17 17:52 UTC
The file `novelwriter-2.3.1-amd64-setup.exe` is detected as malware and quarantined.

This happens on Windows 10 with Windows Defender and no other antivirus of any kind installed. Does not happen in my Windows 10 VM that has no internet access. No previous novelWriter installer has had this issue on my machine.

![2024-03-17___18_29_12](https://github.com/vkbo/novelWriter/assets/60368695/1e47a478-2a33-4faf-a0fd-c6e78f0893bd)

![2024-03-17___18_48_00](https://github.com/vkbo/novelWriter/assets/60368695/ad392ed8-2d31-46e1-b63a-7ac93ffeea76)

"[Lern more](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FWacatac.B!ml&threatid=2147735505)" link to Microsoft

Can someone confirm this? Do you need to do something about this? Do I need to do something about this on my machine?

**Comment by vkbo** [comment] 2024-03-17 18:28
I tested the file downloaded from the website on both my Windows 10 and 11 VMs, and got no warning. I also scanned the installation folder. [VirusTotal](https://www.virustotal.com/gui/file/523b1879e778326046199f2b4e990077bd9fc002f5ccdf52f9ddec16d0915c3c/detection) doesn't really say much either. There are some usual flags from low quality scanners.

It is really hard to say what the is causing the warning. Did you check the checksum of the file?

**Comment by vkbo** [comment] 2024-03-17 18:34
The installer includes the [Qt5 dlls from PyPI](https://pypi.org/project/PyQt5/), and the Windows embeddable version of Python. Neither have been updated on the VM that created this package since the 2.3 release.

It's happened a few times before that virus scanners panic on Python stuff, but I haven't seen it since I stopped using Pyinstaller. Is there any way you can find out exactly what file in the package it is reacting to?

**Comment by vkbo** [comment] 2024-03-17 18:46
Ok, I've submitted the installer to Microsoft. Their preliminary check on their submission form also detects no threats, using definitions 1.407.498.0.

This could be a fluke, as long as you are positive you downloaded the file that is hosted in GitHub (the main website links directly to it) and the shasum is as stated in the sha256 file and on the website.

**Comment by HeyMyian** [comment] 2024-03-17 18:58
Yes, my research on Wacatac.B!ml also made me confident it's a false positive. The `ml` stands for machine learning, so probably no human has seen this.

> Their preliminary check on their submission form also detects no threats, using definitions 1.407.498.0.

Weird, because 1.407.498.0 is the version which detected this on my end.

I can find no further information what exactly would have caused the detection on my machine. The checksum is correct, downloaded from GitHub. I updated now by downloading the source files and overwriting my local files.

I hope it'll be just me and no new user will be detered by this MS nonsense. This is soo annoying 😞

**Comment by vkbo** [comment] 2024-03-17 20:21
is it reproducible if you download the file again and check it? Just so I know in case Microsoft asks for more information. But as I said, their initial scan of the file also resulted in nothing, so this is really strange.

**Comment by HeyMyian** [comment] 2024-03-17 21:16
Yes, the installer file is detected every time. The most information I can get is from the Windows Event Viewer:

> Microsoft Defender Antivirus has taken action to protect this machine from malware or other potentially unwanted software.
 For more information please see the following:
https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Wacatac.B!ml&threatid=2147735505&enterprise=0
 	Name: Trojan:Win32/Wacatac.B!ml
 	ID: 2147735505
 	Severity: Severe
 	Category: Trojan
 	Path: file:_M:\Downloads\novelwriter-2.3.1-amd64-setup.exe
 	Detection Origin: Local machine
 	Detection Type: FastPath
 	Detection Source: Real-Time Protection
 	User: NT AUTHORITY\SYSTEM
 	Process Name: C:\Windows\explorer.exe
 	Action: Quarantine
 	Action Status:  No additional actions required
 	Error Code: 0x00000000
 	Error description: The operation completed successfully. 
 	Security intelligence Version: AV: 1.407.498.0, AS: 1.407.498.0, NIS: 1.407.498.0
 	Engine Version: AM: 1.1.24020.9, NIS: 1.1.24020.9

Nextcloud also refuses to sync to local with the following information, which I've never seen before in Nextcloud. Maybe this is because Microsoft Defender immediately does quarantine the file as soon as the download has finished:

> The checksum header contained an unknown checksum type "SHA1"

![2024-03-17___22_04_45](https://github.com/vkbo/novelWriter/assets/60368695/dfda26f1-6c41-4962-bf61-52700ef24f8c)

Sorry btw you have to deal with this, and thanks again for your work 🙇‍♀️

**Comment by HeyMyian** [comment] 2024-03-17 21:43
For what it's worth, I've just double-checked and none of the installers from previous novelWriter versions are detected.

**Comment by peter88213** [comment] 2024-03-17 22:42
I hate to say it, but it looks like you can't rely on the Windows Defender here. 

In my case, Windows Defender kept quarantining one of my _self-written_ Python programs in the _development directory_ until I had it accept the "Wacatac.B!ml Trojan". 
I went to the bother of sending the script to Microsoft and having it whitelisted. After the next Defender signature update, I could rearm it for "Wacatac.B!ml". 

Two weeks later I changed the Python code, and Defender kicked in again, this time for "Trojan:Win32/MalUri.A!cl". 
Finally I found out that apparently a Python command to copy files to the user profile triggers the Defender.

**Comment by HeyMyian** [comment] 2024-03-17 22:47
I feel the same way @peter88213 

I would just hate if Microsoft Defender detected a false positive on a new novelWriter user. It gives a very bad first impression, although of course completely undeserved.

**Comment by peter88213** [comment] 2024-03-17 22:53
I wonder whether a new generation of AI-driven security software is being developed here. 
In any case, these are bad times for FOSS developers.

**Comment by vkbo** [comment] 2024-03-17 23:30
> Two weeks later I changed the Python code, and Defender kicked in again, this time for "Trojan:Win32/MalUri.A!cl". Finally I found out that apparently a Python command to copy files to the user profile triggers the Defender.

Interesting. What precisely did it react to? novelWriter reads and writes a bunch of files to the user's AppData, of course, since it keeps a lot of config files there.

**Comment by vkbo** [comment] 2024-03-17 23:33
> Sorry btw you have to deal with this, and thanks again for your work 🙇‍♀️

Yeah, I truly and completely hate dealing with Windows.

**Comment by vkbo** [comment] 2024-03-18 10:15
Response from Microsoft. Can you create the file, and send it to me? I'll send you an email address to use via the Crowdin chat.

> Analyst comments:
>
> We cannot reproduce any detection on the file. If the detection is still observed, follow the steps below to capture support log files from the system reporting detection.
>
> From an elevated command prompt, change to directory "%programfiles%\windows defender" and execute mpcmdrun.exe with option GetFiles:
> ```
> cd "%programfiles%\windows defender"
> mpcmdrun.exe -GetFiles
> ```
>
> All created log files will be compressed into MPSupportFiles.cab.  Please send us the detected file and MPSupportFiles.cab using https://aka.ms/wdsi.  We will continue the investigation once we receive the support log files.

**Comment by vkbo** [comment] 2024-03-18 10:19
Actually, you can just submit it yourself via the link above. It doesn't look like I can update my own ticket anyway.

**Comment by peter88213** [comment] 2024-03-18 11:14
> > Two weeks later I changed the Python code, and Defender kicked in again, this time for "Trojan:Win32/MalUri.A!cl". Finally I found out that apparently a Python command to copy files to the user profile triggers the Defender.
> 
> Interesting. What precisely did it react to?

I guess it reacted to the change of the hash caused by minor changes in the code. Actually, a version string in a message was updated. So it was no longer matching the whitelist entry. 

Background: I publish a Python application with ten plugins, each in its own repository. Each individual part can be downloaded as a zip file in order to start an OS-independent Python installation script after unpacking by hand. The installation script quarantined by Defender was always the same one, which differs from all the others in that it copies a template file to the appdata\local area. After I removed this copy command (and replaced it with instructions for manual copying), the Defender stopped alerting.

**Comment by HeyMyian** [comment] 2024-03-18 16:02
> Actually, you can just submit it yourself via the link above.

I tried, but I don't understand where. When I click on "Submit files", all I can upload there is one file which is meant for the intaller.

In the meantime, my antivirus definition version has updated from 1.407.498.0 to 1.407.521.0 and now the installer is not detected anymore.

I can still send you the MPSupportFiles.cab file if you somehow have an option to upload it to Microsoft. Otherwise we can also just close this for now.

**Comment by vkbo** [comment] 2024-03-18 16:12
Ok, maybe they meant I should submit it somewhere, but I couldn't find anything either.

If the issue is resolved with the new definitions, then I guess we can just close this. I'm still concerned that this happened at all, and weirdly only on your PC (as far as we know). Maybe it's an "AI hallucination". We're getting bombarded with those every day these days. 🙄 

It's also possible they added the hash of the installer to their list in the update. They did confirm to me that it was clean.

**Comment by HeyMyian** [comment] 2024-03-18 16:21
> Maybe it's an "AI hallucination". We're getting bombarded with those every day these days. 🙄

Yeah it's looking rather bleak, isn't it.

I'll let you know if this happens again in the future, although at this point I'm unsure what you can even do about it other than to explicitly tell Microsoft that the file is clean. If you knew that a specific piece of the code triggered the detection, I guess you could work around it, but like this....?

**Comment by vkbo** [comment] 2024-03-18 16:28
> Background: I publish a Python application with ten plugins, each in its own repository. Each individual part can be downloaded as a zip file in order to start an OS-independent Python installation script after unpacking by hand. The installation script quarantined by Defender was always the same one, which differs from all the others in that it copies a template file to the appdata\local area. After I removed this copy command (and replaced it with instructions for manual copying), the Defender stopped alerting.

Ah, I see. novelWriter writes a lot of stuff to `AppData\Roaming\novelwriter`, including caching for the Manuscript tool, and when I get around to add support for single file projects (as zip files of the project) they will also be extracted here at runtime. So if the defender dislikes that, it's going to be busy. I'm not sure where else I should be writing app data. This is the location the Qt library returns when requested, as detailed in the [docs](https://novelwriter.io/docs/tech_locations.html).

**Comment by vkbo** [comment] 2024-03-18 16:32
> I'll let you know if this happens again in the future, although at this point I'm unsure what you can even do about it other than to explicitly tell Microsoft that the file is clean. If you knew that a specific piece of the code triggered the detection, I guess you could work around it, but like this....?

I'm going to start testing the file against the defender each time. I guess the defender is less panicky if the file was created on the local machine, so I may need a second VM to check it, or try the report tool.

But yeah, aside from submitting false positives, there really isn't anything I can do. This is precisely why I stopped using pyinstaller, because a lot of antivirus software reacts to it because pyinstaller is also used to distribute actual malware, and the antivirus software vendors implement a rather lazy approach to detecting them. There are tons of threads about this on the pyinstaller repo page.

Anyway, I'm closing this thread since the issue is resolved. Feel free to keep ranting of course. I'm always up for a rant. 😄

**Comment by peter88213** [comment] 2024-03-18 18:06
> I'm going to start testing the file against the defender each time. I guess the defender is less panicky if the file was created on the local machine, so I may need a second VM to check it, or try the report tool.

I don't think that's necessary. Just download it with a Windows browser from somewhere in the repository. 

Concerning the place of creation: As I said, Defender quarantined my source file from my local git working directory, which is excluded from the regular scans, just on trying to open it with the code editor.

When I used the report tool for the first time, it only took a few hours. The second time it took over a week.

**Comment by peter88213** [comment] 2024-03-18 19:30
> novelWriter writes a lot of stuff to `AppData\Roaming\novelwriter`, including caching for the Manuscript tool, and when I get around to add support for single file projects (as zip files of the project) they will also be extracted here at runtime. So if the defender dislikes that, it's going to be busy. I'm not sure where else I should be writing app data. This is the location the Qt library returns when requested,

Well, that is actually the correct approach. Some time ago, long before the trouble with Defender started, I went the same way, installing my application and its plugins and configuration data in a subdirectory of `os.getenv('LOCALAPPDATA')`, which works as well on Windows as on Linux. Then I moved to a directory in the Home root, like `~/.novx`, which is easier accessible for Windows users. That's the way many applications with unix roots set themselves up under Windows, and it doesn't cause problems so far. 

Only one access to the Windows user profile remained, the 'CustomTemplates' directory of a third-party application. And that was it then.

**Comment by vkbo** [comment] 2024-03-18 21:07
> Well, that is actually the correct approach.

Sure, but I'm not convinced Defender thinks it is!

> I don't think that a second VM is necessary. Just download it with a Windows browser from somewhere in the repository.

I'm not convinced. Windows does track where a file comes from, but I'm not sure if it does so by keeping track of where it's stored or the checksum of it. If it caches info on the checksum, the downloaded file will be identical to the one built locally. Most antivirus software checks against checksums.

**Comment by HeyMyian** [comment] 2024-06-13 16:43
Before our lives get too boring, Windows Defender decided the newest version `novelwriter-2.4.4-amd64-setup.exe` has malicious stuff in it and quarantines the installer. The `ml` again means the "malware" is "detected" by **m**achine **l**earning. Checksum is correct.

Learn more link:
https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:Win32/Phonzy.B!ml&threatid=2147772963

![2024-06-13___18_22_03](https://github.com/vkbo/novelWriter/assets/60368695/60b1cd5b-183a-452e-bb37-5bf8ac936cf9)

![2024-06-13___18_20_13](https://github.com/vkbo/novelWriter/assets/60368695/e98faca7-ca19-41db-9762-29aae9d8446e)

> Antimalware Client Version: 4.18.24050.7
> Engine Version: 1.1.24050.5
> Antivirus Version: 1.413.268.0
> Anti-spyware Version: 1.413.268.0

I submitted the file to Microsoft, currently waiting for "final determination".

**Comment by johnblommers** [comment] 2024-06-13 18:15
> The `ml` again means the "malware" is "detected" by **m**achine **l**earning. 

A.I. is going to bite Microsoft in its behind, what with all that hallucinating AI is infamous for. IIRC you have an option to override Defender. Given that this is a brand-new edition of novelWriter, then machine learning has never seen it before, so it cannot possibly know anything about it. Therefore, it has no idea, and like any AI lacking domain knowledge about the material it hallucinates. Classic stuff.

**Comment by HeyMyian** [comment] 2024-06-13 18:42
It's what I did, I installed the new version anyway because I'm not having those shenanigans.

> Given that this is a brand-new edition of novelWriter

The versions between 2.3.1 and 2.4.4 were not detected though. Maybe I didn't try to install them "fast enough" after their release and Windows Defender had "caught on" already by that point? I don't know. I would like there to be a reproducible pattern in the program that our maintainer can change to avoid this false detection, but I guess that'll be wishful thinking for lack of information on Microsoft's part.

I just confirmed with a friend where this version of the installer is also detected by Windows Defender and Chrome, so it's unfortunately not only my machine that's going rogue.

Just please please please please please don't drop Windows as a platform over this 😅

**Comment by vkbo** [comment] 2024-06-14 05:32
I will not drop Windows over this, but there is also nothing whatsoever I can do about it. You have to submit the false positive to Microsoft. I can't do it myself unless I can reproduce the issue as you must include the log to submit it. These days I scan the package with Defender before I upload it. Also this time I got no warning, so this is most definitely not consistent.

**Comment by vkbo** [comment] 2024-06-14 05:57
You may have a point about there being a delay, because I got no detection when scanning it before upload, but it does give the false positive if I scan it now. That is doubly annoying, because then my pre-scan is just pointless ...

Anyway, I submitted it to Microsoft.

**Comment by vkbo** [comment] 2024-06-14 06:01
Also on VirusTotal: https://www.virustotal.com/gui/file/cc446888ebfaea9d42f667ee32c54b58862d10173cd2814e1e4291a6786d1d09?nocache=1

It is clear that the big commercial scanners don't detect any virus. I've never seen that on novelWriter I think. So it's just these crap ML and freeware scanners that do.

**Comment by vkbo** [comment] 2024-06-14 06:03
I'll just leave this ticket open so I can get updates on new releases being flagged.

**Comment by vkbo** [comment] 2024-06-14 06:49
@HeyMyian, can you do a scan on the file after you've accept it? So that you can see it starts scanning through all the files packaged in the installer?

If I do that, I get no threats detected by the same version of Defender that flags it as malware if it just checks the signature.  I suppose that is why it detects nothing when I scan after building the installer. It knows the file is local, and probably scans it differently.

My false positive report to Microsoft also does a scan. The online scanner gets the false positive, but the scanner version I have does not in their report either. Which is weird, but maybe there are indeed two modes to run Defender in.

![image](https://github.com/vkbo/novelWriter/assets/1619840/cb245dba-c3dd-4652-8839-caec961a5800)

**Comment by HeyMyian** [comment] 2024-06-14 09:34
It doesn't find any threats when I scan the file after I've allowed it. I assume 1794 is the number of files inside the exe?

![2024-06-14___11_12_22](https://github.com/vkbo/novelWriter/assets/60368695/de69996b-5cff-4408-86ee-8e9189e26009)

> My false positive report to Microsoft also does a scan. The online scanner gets the false positive, but the scanner version I have does not in their report either. Which is weird, but maybe there are indeed two modes to run Defender in.

I had also submitted the installer to Microsoft, and I'm seeing the same thing.

**Comment by vkbo** [comment] 2024-06-14 09:45
Even the screenshot from their own tools confirm this. I bet the "Client" also makes the same scan, while the "Cloud" behaves the way the download process does. Just a guess anyway, but at least this time they have a confirmed positive they can check against. Last time, the online tool cleared it even if you got a local warning.

Anyway, 1794 is probably about right. I think that's what I get too. There are a ton of files associated with the Qt5 framework. I also delete a lot, including the whole webengine framework it comes with as well as the QtQuick framework that novelWriter doesn't use.

The false positive may very well stem from the installer itself, and not any of the novelWriter code. The Windows installer is built with Inno Setup, which is a very common free tool for building installers. I've considered switching to Microsoft's own, but as everything made by Microsoft, it's incredibly clunky to use and set up. I don't really want to install Visual Studio either.

**Comment by HeyMyian** [comment] 2024-06-14 09:52
It must be the installer itself, I think. Scanning the novelWriter directory in /ProgramFiles gives no results whether I allow or disallow the installer.

If the false positive detections will continue in the future, is there maybe a way to distribute novelWriter as single portable exe file that has all the necessary nw and python files bundled within? I've read that somewhere as suggested solution for these detections (with NSIS). When the "problem" is that the current installer extracts a bunch of files into /ProgramFiles, *not* extracting a bunch of files might be a good idea.

**Comment by vkbo** [comment] 2024-06-14 09:57
I've tried the single exe file approach. It triggers way more virus false positives than this approach. I also found the single exe approach to be quite slow, but it may be faster if the Qt libraries are not bundled into the exe. The startup time is dependent on the exe size.

In the past I distributed novelWriter as a plain zip file with an install script that created the desktop shortcut with the correct startup command. It is essentially the same as what the installer does, but it was more clunky to use for non-technical users.

Of course, `pip install novelwriter` is always an option too for anyone with a Python env already set up. 😃

**Comment by vkbo** [comment] 2024-06-14 13:38
So, did some testing after researching a bit. and it may very well be Inno Setup is part of what the ML checker detects. ML algorithms are after all pattern detectors, and are known to detect the wrong patterns as it has no concept of the difference between correlation and causation.

In any case, I also found a few suggestions that zip packaging in Inno Setup is less prone to false positives than lzma. Not sure if it is true, but I just built a new installer with zip packaging, which increased the size by about 12 MB, and also with Inno Setup 6.3.1 which is a recent release that the naive ML detectors haven't seen used by actual malware yet.

This produced an installer with no warnings, even for the really crap anti-virus tools: https://www.virustotal.com/gui/file/926eddce24e9d5006d3d8801ffd4617994e71d56b987aa8669dd611efd7b0216

I'll update the build process with these settings for the next release, but if Microsoft clears the current 2.4.4 installer, I will probably leave this one as-is.

**Comment by HeyMyian** [comment] 2024-06-14 14:20
Thanks for your effort. Fingers crossed it'll work for the future 🤞

**Comment by vkbo** [comment] 2024-06-14 14:51
I just dished out 589€ for a code signing certificate, so maybe that will help a little in the future too.

Such an open source friendly platform ... 🙄

**Comment by vkbo** [comment] 2024-06-18 10:25
Ok, that fell through. Trying to get a certificate from somewhere else.

In the mean time, Microsoft has done exactly nothing about the false positive. Good thing I built a new installer, so it doesn't matter. I'll start running the installers through VirusTotal before release again. It is clearly not enough to just scan them locally with Defender.

**Comment by vkbo** [comment] 2024-06-25 10:51
Suddenly the 2.5 RC 1 installer was flagged too by Edge download, but I submitted it and nothing was detected by the tests they run for submissions. I honestly have no idea why the download action flags it but their own tools do not when run manually. Maybe this is the BS ML part.

![image](https://github.com/vkbo/novelWriter/assets/1619840/7b69b1db-0a28-4741-965f-475136ae382e)

**Comment by HeyMyian** [comment] 2024-06-25 14:20
It's being detected and removed on my machine with definition version `1.413.508.0`, which is *wild* when comparing to your screenshot.

![2024-06-25___16_15_08](https://github.com/vkbo/novelWriter/assets/60368695/71f03d7b-404a-4fad-b70d-521e7ebf3aa4)

**Comment by vkbo** [comment] 2024-06-25 17:52
Yes, same when I try on both Windows 10 and 11. This is just plain absurd and impossible to work with.

**Comment by vkbo** [comment] 2024-06-25 18:04
Ok, `1.413.510.0` is available now, and with the definition updates it downloads the installer without any issue.

**Comment by HeyMyian** [comment] 2024-06-25 19:21
I'm now on definition `1.413.517.0` and it quarantines 2.5rc1 🙃

**Comment by vkbo** [comment] 2024-06-25 19:26
Hmm, I got `1.413.517.0` too now, and could download and install it. This is all over the place ...

**Comment by vkbo** [comment] 2024-06-25 21:24
As for false positives in general, I checked in on how pyinstaller is doing on that front, and it's a [train wreck](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

I was considering testing with pyinstaller again, because it is a great tool ... but 😒

**Comment by vkbo** [comment] 2024-09-18 14:23
Good news! The novelWriter installer for Windows is now signed, which should help a lot. The code signing is provided by SignPath for free. It's the same used for the Windows installer for Vim and other apps.

I also removed all the links from the credits page and about dialog, which also seems to have helped with virus scanning, even before that. A lot of URLs looks suspicious apparently.

**Comment by vkbo** [comment] 2024-11-08 21:12
Closing this now as it won't get any better than it is now, with the signed Windows installers. There's been two signed releases, and it seems to be fine.

**Closed by vkbo** 2024-11-08 21:12 UTC
Labels: installation
