### ISSUE TITLE
Dragging dividers is sluggish when a 65,000-word document is open

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#150] opened 2019-11-17 21:24 UTC
In version 0.4.2 of novelWriter:

1. Double-click a scene containing a 65,000-word document (it was imported from an old NaNoWriMo draft manuscript) and 
2. Type <kbd>Ctrl</kbd><kbd>R</kbd>. Now both the editor in pane 2 and the preview in pane 3 are visible.
3. Now drag on either divider to resize the panes. It's a sluggish experience. novelWriter takes about a second to reflow the text, and this is on a fast Linux machine.

In the editor preferences I have unchecked _Max text width_ and _Justify text_, checked _Show tabs and spaces_, checked _Show line endings_. Spell check is off. The theme is set to default dark

**Comment by vkbo** [comment] 2019-11-17 22:31
Yeah, there isn't much I can do about that. It is caused by the underlying Qt framework needing to redraw the document due to changes in word wrapping. I can add a flag that waits to redraw the documents until you've released the mouse, which means it will only have to do it once. I'll look into optimising the pipeline to see if there's anything I can improve. I know the spell checker is run twice on the active document when a project is opened.

The editor itself should be fairly responsive with only 65000 words. I've tested it up to a few million words. It gets increasingly sluggish, but only at many 100k words. The highlighter and spell checker are only run once when the document is opened, and after that it is run only on the paragraph you're writing on. They can of course be slow on the initial checking and highlighting. That said, I should probably disable these features automatically if the documents are too large. I need to do some performance checks again on my 840k words test document.

Also, to reiterate, the right hand panel isn't a preview panel. It's a view panel for having reference documents open when writing. Issues like this is why I am reluctant to have it regenerated live from the document being edited.

**Comment by vkbo** [comment] 2019-11-17 22:45
Aha, found one issue. The document is also re-highlighted when it is redrawn due to a resize. I'll see if there's a way to avoid that.

**Comment by vkbo** [comment] 2019-11-18 09:13
Again, this is something seemingly out of my control. The highlighter is reapplied after the document is redrawn. As far as I can tell there is no way around this without having to write a new highlighter class, which isn't going to be very efficient in pure Python.

There are a number of discussions on this topic on the Qt forum.

I will look into a few improvements that reduces the load when re-flowing the text, but until Qt improves the highlighter class, I'm not sure there is much I can do without diving into C++ and subclass it.

Possible improvements:
* Disable opaque resizing of QSplitter.
* Disable the highlight class when a document is opened, or a view is opened, until the documents are drawn.
* Disable rehighlighting when turning on and off the spell checker (this is incredibly slow on a large document, it took several minutes on my 840k word text, so clearly a bug somewhere).

**Comment by vkbo** [comment] 2019-11-19 09:33
I think I have a solution. I'll detail it here both for my own record, and because GitHub issues are indexed and searchable, so it may be useful to others.

It was clear that the re-highlighting of the entire document on resize was triggered from the Qt side of things. I spent some time last night looking through the Qt source code for the QSyntaxHighlighter class. The highlighting is run on a per-block (paragraph) basis, starting from a given position, and a given number of altered characters ahead. The highlighter gets this information by connecting to the contentsChange signal of the QTextDocument. This signal contains position, characters removed and characters added.

Curiously, when the root frame of the document is modified, the contentsChange signal is emitted with position 0, all characters removed and all characters added again. Effectively, that triggers a re-highlighting of the entire document.

Since resizing the text window manipulates the document root frame to ensure the text width and margins are handled according to user settings, the resize triggers this entirely redundant re-highlighting. This can be bypassed by blocking signal emission for the QTextDocument and re-enable it immediately before and after the update of the root frame. This stops the re-highlighting altogether.

I will make a patch right away, since it's a simple two line fix.

**Comment by vkbo** [comment] 2019-11-19 09:48
Note that there are several remaining performance issues related to syntax highlighting and spell checking for large documents. I think these can be best addressed by trying to move these features out of the main loop and into separate threads. That seems to be how other applications deal with these tasks.

**Comment by johnblommers** [comment] 2019-11-19 18:37
Good point. I have a 200,000-page[^MS] text document that consists entirely of [Lorem Ipsum  text](https://lipsum.lipsum.com/). I use it to stress test text editors and the spell check overhead/latency really shows. The red underlines will wash over new text as it's scrolled into view.

IMHO nothing except `vi` can beat [**Kate**](https://kate-editor.org/) for handling vast text files with buttery smoothness. Nothing.

[^MS]: Motivated by a comment by globetrotter at [this article](http://www.antipope.org/charlie/blog-static/2013/10/why-microsoft-word-must-die.html).

**Comment by vkbo** [comment] 2019-11-19 19:57
Spent a lot of time today performance testing and tweaking novelWriter for large chunks of text. I mean, it should be able to handle a long novel in a single file. I've been using a single mardkown file containing the King James bible of about 4.2 Mb. It's an excellent stress tester.

So, with the spell enchant enabled, it took me 9.1 seconds to load it on my computer. Disabling spell checking took it down to 0.8 seconds, and improving the syntax highlighter further, I git it down to 0.42 seconds on average.

The solution I think I will implement for now is to have initial spell checking disabled for files over a certain size. The user can set this limit. By default it's 800 kb, or ~120k words. Spell checking then switches to be only active as you type, so it will only spell check the paragraph you're working on. If you're happy with a 2-3 second or more lag when opening files, than it can be kept active all the time, but the user has the choice.

The problem is really the implementation of the QSyntaxHighlighter. Since I've built the application in Python, overloading the core functionality in the library with Python code is going to slow it down considerably. The only viable option really is to rewrite the C++ code.

I'm considering adding a background process that checks what paragraphs are visible in the editor as you scroll, and then run the spell checker on those only, but I'm not sure if the need is that great for supporting ~1M text files.

The real penalty of spell checking becomes apparent if you use the basic spell checker that I added for when enchant isn't installed. It's about 10 times slower than enchant, and opening the 4.2MB file would take 1-2 minutes.

**Comment by vkbo** [comment] 2019-11-19 20:09
I've tested the QTextEdit class that novelWriter uses with up to ~50 Mb files, and the editor handles it just fine. The syntax highlighter slows down a bit, but not enough that it becomes unusable. The bottleneck really is spell checking - and specifically, looking up every single word in a 500k+ words document during initialisation.

I need to look into implementing SymSpell as the main spell check tool. Its algorithm is significantly faster than the conventional one used in most spell checkers. With it, even a 1M words document should be manageable.

**Comment by vkbo** [comment] 2019-11-19 21:10
Performance issues addressed in PR #154

**Comment by johnblommers** [comment] 2019-11-19 22:25
I downloaded the master zip file and checked out novelWriter's new divider behavior using the 4.2 MB  King James Bible text file that I downloaded from Project Gutenberg. I kept the spell checker turned off. Dragging on the vertical divider bars is a good experience. 

Let me note that the King James Bible text file consists of mostly short lines so the overhead of rewrapping text in the editor pane is lighter. The document pane has the wonderful feature of reconstituting the paragraph of each verse and has no problems rewrapping  text. 

novelWriter  responds very well to both dragging the dividers and resizing the noverWriter window.

But when I turn on spell-check with King James Bible loaded,  novelWriter becomes unresponsive, the system then offers me the chance to kill it, which I accept. Given this is testing on a development version, I believe I have gotten ahead of myself again ;-)

**Comment by vkbo** [comment] 2019-11-20 10:03
Thanks for testing.

Yeah, I don't use the plain text version of the KJV. I use a copy/paste of the html version wich I manually went through and set the headers for. The performance difference is n't significant, but short lines aren't necessarily a bonus as it actually means there's a lot more lines to iterate through, which adds overhead.

What you experienced is not a hang. It is just busy running the slow spell checker. It will eventually finish if you leave it. I'm considering adding a progress bar for it that is enabled automatically on long documents.

The internal spell checker does a dictionary key lookup of the entire dictionary on each word check, so it is incredibly slow. About a factor 10 compared to enchant. At least. It will appear to hang in the meantime because the spell checker unfortunately runs on the GUI thread. This is because the QSyntaxHighlighter that does the spell checking must run on the GUI thread because it is connected to a GUI object (the QTextDocument).

If you start novelWriter with the `-d` and `--verbose` flags, you should see a printout of the timing information of the highlighter in milliseconds.

**Comment by johnblommers** [comment] 2019-11-22 19:53
> I'm considering adding a progress bar for it that is enabled automatically on long documents.

It's good for the user to have feedback. Back in the day, say with macOS 7, when a GUI application got busy, it always put up a spinning cursor so the user knew it wasn't listening for interface events. 

These days it has become common for busy applications to leave the mouse pointer alone and  just ignore mouse clicks and key presses when they're busy. Let me applaud your efforts at making novelWriter more user-friendly.

**Comment by vkbo** [comment] 2019-11-27 17:35
I think with the changes of PR #158, the things needed for this issue to be resolved are in.

**Closed by vkbo** 2019-11-27 17:35 UTC
Labels: enhancement, user interface
