### ISSUE TITLE
Modal windows prevent alt-tabbing if novelWriter is in full screen mode

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1492] opened 2023-07-30 14:19 UTC
Steps to reproduce:

1. Put novelWriter into full screen mode (F11)
2. Initiate Build Manuscript
3. Click on the button "Build" or "Print"

Expectation:

* Let me tab out of novelWriter

Behavior:

* I'm forever stuck on this window until I take another action.
* The modal window "file exists, do you want to overwrite the file?" again lets me tab out.

The issue already existed in 2.0.7

---

Here are two screenshots of the "stuck" state:

![Screenshot_2023-07-30_15-58-09](https://github.com/vkbo/novelWriter/assets/60368695/512bfa3e-e66d-4661-bbc3-cc4d68dfe52f)
![Screenshot_2023-07-30_16-07-00](https://github.com/vkbo/novelWriter/assets/60368695/f0c7e6e0-d241-4782-a6ee-478054384594)

**Comment by vkbo** [comment] 2023-07-30 14:38
I cannot reproduce this. What OS, distro and Window Manager are you using?

**Comment by vkbo** [comment] 2023-07-30 14:46
The build tool and build settings dialogs are non-modal by the way, but the others are modal. Maybe that's what's causing the problem.

**Comment by HeyMyian** [comment] 2023-07-30 14:48
This is KDE neon 5.27 with KWin, all fresh up to date.

I tried similar behaviors in Libre Office and Firefox--that is, put application into full screen and check if the "file save" dialogue or the "print" dialogue lets me tab out, which it does. Which other thing could I try that is more similar to how novelWriter handles these windows?

**Comment by vkbo** [comment] 2023-07-30 15:04
I'll install it in a virtualbox and play around. Maybe the way I'm handling non-modal dialogs is the problem. It could also be what causes the issue on Mac as mentioned in the release discussion.

**Comment by HeyMyian** [comment] 2023-07-30 15:08
The "open project" > "choose path" window has the same issue btw.

**Comment by vkbo** [comment] 2023-07-30 15:10
Hmm, ok, these are both modals, so maybe the issue is something else then. Maybe a modal dialog opening another modal dialog is the problem.

**Comment by HeyMyian** [comment] 2023-07-30 22:47
> Maybe a modal dialog opening another modal dialog is the problem.

I tested several other instances where a modal opens another modal, and this seems to be the case. When the parent modal __cannot__ get focus while the child is there, I can't tab out.

The modals around the "Build" function are a little different case, because "Build Manuscript" can get focus (i.e. can be interacted with, I don't know the jargon) at the same time as its child "Manuscript Build Settings" is there. As far as I understand, it's the only modal that does that, all the others I tested (Stats > Save as, Preferences > Quote style selection, Preferences > Backup storage location...) don't allow interaction with their parents.

There are these little dialogue popups that seem to be different. These constellations allow alt-tabbing even when they're focused and their parents can't be focused:
[Screenshot_2023-07-31_00-12-17](https://github.com/vkbo/novelWriter/assets/60368695/07840291-35d7-46f7-a20e-d1bcdd681879)
[Screenshot_2023-07-31_00-32-12](https://github.com/vkbo/novelWriter/assets/60368695/fe9c8896-26aa-4590-a77c-81ce5cfec5ff)

All this is only a problem btw when novelWriter is in full screen mode (F11). If it's maximized or whatnot, this is not a problem.

Are these real issues or am I just bored and procrastinating?

**Comment by HeyMyian** [comment] 2023-07-30 23:09
With the new information, I just double-checked Libre Office and Firefox. They exhibit the same behavior in full screen. I tried the save file dialogue which then prompted me with a "are you sure you want to overwrite?", as well as some other modals that spawn children, and at that point alt-tabbing is impossible.

I think you can close this.

**Comment by vkbo** [comment] 2023-07-30 23:10
Most dialogs are modal (which is standard). They block interaction with the main window when they are open. I try to avoid this for the tools as they may be open while you're working. Especially if you have more than one screen.

The non-modals are the Build Manuscript Tool, Build Settings, Writing Stats, and one or two more. I have no idea why KDE should behave differently in full screen mode than normal mode. There is no difference on Gnome+Wayland at least, and I cannot remember having an issue with Gnome+Xorg either.

I'm not sure if this is fixable, or out of reach from the novelWriter source. Most of the negotiation with the desktop window manager is handled deep within Qt in a bunch of OS-specific code.

**Comment by vkbo** [comment] 2023-07-30 23:11
> With the new information, I just double-checked Libre Office and Firefox. They exhibit the same behavior in full screen. I tried the save file dialogue which then prompted me with a "are you sure you want to overwrite?", as well as some other modals that spawn children, and at that point alt-tabbing is impossible.
> 
> I think you can close this.

Hmm, that definitely sounds like something on the window manager level then.

I'll close this then 😃

**Closed by vkbo** 2023-07-30 23:11 UTC
Labels: bug, build tool
