### ISSUE TITLE
Chapters, scenes, and note folders are not translated in new projects

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1751] opened 2024-03-12 15:45 UTC
When creating a new project populated with empty chapters, scenes, and note folders, these items are created with English labels in the novel tree. It seems to me though that we should already have all of those words as translations, so the translations should probably be used. The Example Project can stay as it is, imo.

**Comment by vkbo** [comment] 2024-03-12 17:46
I cannot reproduce your issue. It worked both for Norwegian and German when I tested:

![image](https://github.com/vkbo/novelWriter/assets/1619840/989f4250-4b61-4393-a82d-dbddf12b1863)

**Comment by HeyMyian** [comment] 2024-03-12 18:35
I can confirm that it works correctly. I must have been mistaken, creating the project with English language and then setting the language to German afterwards what with my unorganized testing today.

**Comment by vkbo** [comment] 2024-03-12 19:50
Ok, closing this then.

**Closed by vkbo** 2024-03-12 19:50 UTC
Labels: localisation
