### ISSUE TITLE
Implement Find and Replace for all matching strings

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1328] opened 2023-01-29 04:43 UTC
String replacement _for all found matches_ is currently missing. The user has to click through every single match found in the document/project. Some search results can be in the hundreds... That's too much clicking.

Text editors usually allow the user to click a separate "Replace All" button, which is along the lines of what I'm requesting here.

**Comment by vkbo** [comment] 2023-01-29 10:48
This is a duplicate of #545. The feature is coming 😄

**Closed by vkbo** 2023-01-29 10:48 UTC
Labels: duplicate, enhancement

**Comment by tmarplatt** [comment] 2023-01-29 11:31
Weird, I did search before submitting. 😐

**Comment by vkbo** [comment] 2023-01-29 11:34
Yeah, the search here isn't always great. I knew there was a request for it, so I just looked through the pages.
