### ISSUE TITLE
Add keyboard shortcuts to cycle through entire chapters

### ISSUE THREAD

**Issue by marek-lach** [vkbo/novelWriter#1348] opened 2023-02-06 18:00 UTC
Add the keyboard shortcut(s) `CTRL + SHIFT + Up`, and correspondingly also `CTRL + SHIFT + Down` to cycle selection through entire chapters (at their root level, skipping over the individual scenes within), without, however, moving them in hierarchy. For quicker, easier navigation of long projects.

Inspired somewhat by the keyboard-centric navigation of [this](https://github.com/brsloan/warewoolf).

**Comment by vkbo** [comment] 2023-02-06 21:23
So, basically you want a keyboard shortcut to skip between chapter files in the project tree? It's a fairly neat feature, I agree.

Since it is up to the user to decide how the project is organised, it may not be organised into levels in a strict "chapter > scene" sort of way. So perhaps a more general solution is needed. Here's a counter proposal:

How about two shortcuts to jump to the previous/next item of the same kind? If you're on a document that is a chapter, it will jump to the next chapter. If it's a folder, it jumps to the next folder, note for note, scene for scene, partition for partition ... you get the idea.

I'm also not sure about the `Ctrl+Shift+Up/Down` shortcut. How about `PgUp` and `PgDown`?

**Comment by vkbo** [comment] 2023-02-06 21:33
I could add two entries in the "Quick Links" menu as well, with "Jump to Previous" and "Jump to Next" which will have the shortcuts listed. That way they should be easy to discover for the exploring type of user.

**Comment by marek-lach** [comment] 2023-02-07 15:03
> How about two shortcuts to jump to the previous/next item of the same kind? If you're on a document that is a chapter, it will jump to the next chapter. If it's a folder, it jumps to the next folder, note for note, scene for scene, partition for partition

Oh yes, that is the correct idea, I just articulated it poorly. It occurred to me afterwards that I should have written this would mean the ability to jump from an entire folder to another folder etc. in one swoop with a keyboard shortcut.

> How about PgUp and PgDown

That is certainly more intuitive from the user's perspective, and easier to remember, sure.

**Comment by vkbo** [comment] 2023-02-07 15:36
> Oh yes, that is the correct idea, I just articulated it poorly. It occurred to me afterwards that I should have written this would mean the ability to jump from an entire folder to another folder etc. in one swoop with a keyboard shortcut.

Ah, so the original idea was to jump between chapter folders. Which assumes the user has folders for chapters, which is not a given. But my proposal would then work for all cases more or less. The project tree now knows what the first heading of a document is, so it can figure out how to jump correctly.

> > How about PgUp and PgDown
> 
> That is certainly more intuitive from the user's perspective, and easier to remember, sure.

Just since `Ctrl+Up/Down` moves the items, it may be too easy to make a mistake with `Ctrl+Shift+Up/Down`. Perhaps `PgUp/Down` are not the right shortcuts though, as they actually skip a "page" in the tree to the next place scrolled out of view. That is a useful feature to preserve. So perhaps `Shift+Up/Down` instead. As long as it doesn't produce accidental `Ctrl+Up/Down`, it's all good.

With `Shift+Up/Down`, I could also make `Shift+Left/Right` jump up or down a level in the hierarchy. Pressing just `Left` already does this if the item is a leaf node, but if it is a tree node it closes it. I could also make `Shift+Home` jump to the current root folder as well.

Those would all make for some neat quick nav features for the project tree. The problem is providing a sensible way for users to discover them. It doesn't really make sense to add them to a menu. I may need a cheat sheet feature or a keyboard shortcut panel that lists them all.

**Comment by marek-lach** [comment] 2023-02-07 16:36
> But my proposal would then work for all cases more or less. The project tree now knows what the first heading of a document is, so it can figure out how to jump correctly.

Very true. It's a better proposal.

> So perhaps Shift+Up/Down instead. As long as it doesn't produce accidental Ctrl+Up/Down, it's all good.

For sure.

> With Shift+Up/Down, I could also make Shift+Left/Right jump up or down a level in the hierarchy.

Oh, that is cool!

Those would all make for some neat quick nav features for the project tree. The problem is providing a sensible way for users to discover them. It doesn't really make sense to add them to a menu.

I don't think so either. They should certainly just be keyboard shortcuts only for now. Some mention in the manual may suffice. With perhaps something like `ALT`, or an `F1` key bringing up a window with all of the available keyboard shortcuts written out in some future version...?

**Comment by marek-lach** [comment] 2023-02-07 17:17
> I could add a quick link from the Help menu that goes directly there. I'm reluctant to add too much info into the GUI as it would need translations. I only have a limited number of translation words available in Crowdin, and at the moment it's enough for 17 languages.

That seems reasonable. Since `F1` already loads the online user manual, perhaps a new item under `Help > Keyboard shortcuts` mapped to like `Alt` could redirect straight to [them](https://novelwriter.readthedocs.io/en/stable/usage_shortcuts.html ), and that would be it.

**Comment by vkbo** [comment] 2023-07-29 20:46
I've added the following (copy/pasted from the PR):

* `Shift+Up` and `Shift+Down` navigates up and down the project tree between sibling elements under the same node. Navigation stops at the boundaries. This is different from normal `Up` and `Down` navigation, which moves between rows and ignores the tree structure. The new functionality is mostly useful on the higher levels as you can skip all expanded child items.
* `Shift+Left` navigates to the immediate parent of the selected item, stopping when reaching a root item. This is only marginally different than the `Left` key which will alternate between closing an item and moving to the parent, depending on the item's state.
* `Shift+Right` navigates to the first child of the item, expanding it in the process. This too is only marginally different than `Right`, but it combines expanding and moving in one keypress.

----

The first one is probably the most useful. If you have a consistent structure, and all chapters start at the same level, with scenes as child elements, this will let you skip between them. I also found it convenient for skipping between root folders.

The second one is also useful because it lets you navigate to parent items without closing the nodes, which the regular `Left` key does.

The last one is only there for completeness, and has only marginal usefulness. It basically expands and navigates to first child in one go, rather than having to press the `Right` key twice to achieve the same. If the nodes are expanded, `Shift+Right` and `Right` behaves identically.

**Closed by vkbo** 2023-07-29 20:46 UTC
Labels: enhancement, project management, next release

**Comment by vkbo** [comment] 2023-07-29 20:51
Hmm, it just struck me that `Shift` may be a risky modifier to use, as it is usually used for multi-select. The novelWriter project tree doesn't allow for multi-select right now, as there are no features that currently need it, but using `Shift` in this manner may be confusing to people, and will block me from enabling it later on.

Perhaps it is better to use `Alt` as the modifier instead.

The changes have only been merged to the dev branch, so nothing is released yet.
