### ISSUE TITLE
Hidden Text Feature

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#400] opened 2020-08-14 03:18 UTC
**Is your feature request related to a problem? Please describe.**

When making an edit pass over a manuscript I sometimes come across a chunk of text that I want to remove. But it's text that I might want to put back or use again later on. How can this text be maintained available and yet not have it show up in the manuscript?

novelWriter already includes a comment feature so the writer can sprinkle the text with ideas and notes. But the text I want to hide is not a comment. It might be a description of an object, place or person.

**Describe the solution you'd like**

I propose novelWriter include special markers, perhaps backtics:  `\`hide this text`\`. A user controlled switch will:

- reveal all hidden text but change its color so it's obvious
- hide all hidden text (to display the manuscript as it will be exported)
- search inside only the hidden text (so the writer can find it again)
- don't include hidden text in the exported manuscript (default)
- do include hidden text in the exported manuscript (not sure how this is helpful)

**Describe alternatives you've considered**

This sort of thing may be possible if novelWriter were to include Git integration. There is a feature request to add Git integration that might be pressed into service to accomplish the above. However the above seems so much more useful. 

**Additional context**

None.

**Comment by vkbo** [comment] 2020-08-14 07:26
Duplicate of #399

**Closed by vkbo** 2020-08-14 07:26 UTC
Labels: enhancement
