### ISSUE TITLE
novelWriter not opening

### ISSUE THREAD

**Issue by AKPhoto** [vkbo/novelWriter#772] opened 2021-05-05 19:12 UTC
So I was using novelWriter which I personally love. Today when I try to open it it throws out an error that the folder doesn't exist. I tried reinstalling but when I click on the shortcut nothing happens.

**Comment by vkbo** [comment] 2021-05-05 22:05
Could you please provide some more information about how you got this error? There is a bug template you should follow, otherwise there is very little I can do as I don't know how to reproduce the problem on my own computer and fix it.

* Which version are you running?
* What steps did you take leading up to the error?
* Is there an error box opening? If so, what does it say?
* Does novelWriter crash or is there just a message you can click "OK" on?
* Which folder is missing? A folder from your project, or some folder internally in novelWriter?

**Comment by vkbo** [comment] 2021-05-05 22:12
Is that the same problem you reported before? If so, it isn't a bug, just something wrong with your setup. I've already responded here: https://github.com/vkbo/novelWriter/discussions/771

**Comment by vkbo** [comment] 2021-05-06 08:43
Closing this as it is related to the already existing help request and not a bug in novelWriter.

**Closed by vkbo** 2021-05-06 08:43 UTC
Labels: duplicate
