### ISSUE TITLE
Project Index permanently outdated / broken

### ISSUE THREAD

**Issue by ben-albon** [vkbo/novelWriter#1020] opened 2022-03-16 22:37 UTC
I'm going to need some help with fault finding this bug - apologies.

I have a project that I've been working on through various versions of the app.  Since upgrading to version 1.6 of the app, whenever I open this project I am presented with the following **Warning** - "The project index is outdated or broken. Rebuilding index."

I click OK, and am presented with the following **Information** - "The project index has been successfully rebuilt."

But this happens again whenever re-open the project.  All actual data is saved, but the index is constantly in need of being rebuilt.

Other projects don't present this behaviour, so I suspect this is an issue with one of the documents in this specific project.

Windows 10, NovelWriter version 1.6.

I've tried restoring the project from backup, and the problem persists.

Please let me know what else I can do to troubleshoot!

**Comment by vkbo** [comment] 2022-03-16 22:50
This is very likely caused by the changes made due to request #957. The index is now also rebuilt if novelWriter finds a document in the project that isn't indexed already. Clearly there is a document in your project that falls between the cracks here and triggers this every time.

The loaded index is just a cache between sessions to avoid having to load all document every time you open a project. The notification is completely harmless, although I can see why it's a bit annoying. You can safely ignore it until I've identified the issue and fix it.

**Comment by vkbo** [comment] 2022-03-16 23:14
Ok, I managed to trigger this as well. It can be caused by a document that has lost some meta data.

Do you have any documents in your project where the "Usage" label in the details panel below the project tree says "None"? If so, that document would definitely cause this issue. You can fix it by editing the document details (F2) and set "Layout" to either "Project Note" or "Novel Document". At some point that information has probably gotten lost.

If that info is lost, it defaults to "No Layout" which is excluded from the index, and thus will always trigger the missing-in-index-check I mentioned. I'll see if I can find a better way to handle such cases.

**Comment by ben-albon** [comment] 2022-03-16 23:26
Just the _**trash folder**_ (which I cannot change the document details for).

That does appear to be the source of the issue though.  I've tested with another project that also has a trash folder, and the same issue occurs. Other projects (without a trash folder) do not have this issue.

**Comment by vkbo** [comment] 2022-03-17 07:15
No, it's not the folder itself. Folders are not indexed.

Another thing that can cause this from an old project is if you have an empty document in the project tree. It should have word count 0. In recent releases, new documents are always populated with a title, so entirely empty files don't exist in the project folder on disk any more. If that is the cause, you can fix it by opening the document and do "Document > Save Document" or press Ctrl+S. That will force a new index entry to be created, which should solve the issue.

This is a corner case I hadn't considered. I do test conversion from older project formats in the test suite, but it doesn't cover all possible scenarios. I'll make a fix that deals with this as well as the "No Layout" case. It is pretty obvious the check for the index has become a bit too strict for all possible cases in "the wild" so I'll relax them a bit. There's no need to alarm or annoy the users with this as there is no real problem with the actual data.

**Comment by ben-albon** [comment] 2022-03-17 09:20
I deleted some (completely) empty files from the trash bin, and added a # header to some **Project Note** files that were missing it - and that's done the trick

Thank you for the help!

**Comment by vkbo** [comment] 2022-03-17 11:19
Great! Then we've identified the underlying issue.

The loop that re-indexes the documents if the index is incomplete skips empty files, but the check expects them to be there still. Opening and manually saving the document uses a different path which forces an indexing also on empty files, so that's the cause of the inconsistency. You don't actually have to add anything to the docs to fix it, but it doesn't hurt of course.

The simple solution is to just allow the re-indexing loop to also index empty files. I'll make that fix later today. It may be worth a new patch release. Not sure how many people this affects.

**Comment by vkbo** [comment] 2022-03-20 15:19
I just merged a fix and made a 1.6.2 release that should fix this.

**Closed by vkbo** 2022-03-20 15:19 UTC
Labels: bug
