### ISSUE TITLE
Lose the space after the period.

### ISSUE THREAD

**Issue by mcrislip** [vkbo/novelWriter#1463] opened 2023-06-11 00:02 UTC
I do most of my writing on Linux/Zorin 16.2. Occasionally I need to use a mac (ventura 13.4). Both have the same, most recent version of NovelWriter.

I just noted that on the mac side, all the single spaces after a period and comma are gone.

They are maintained on the linux side.  On the mac, after you type a period or comma, then space,  and start the next word, the space goes away. However, on the linux side the space is there. And if you correct the problem in the mac side so you see a single space after a period or comma, you get two spaces on the linux side.  Kind of odd.

**Comment by vkbo** [comment] 2023-06-11 02:54
There was a similar issue reported before, and then it was a font issue. In either case, the text editor itself is provided by the Qt library, so and I don't control the rendering of the text itself.

Could you try switching editor font on novelWriter on the Mac?

**Comment by mcrislip** [comment] 2023-06-13 22:54
I tried arial and new times roman on new projects.
problem is the same.
Not that big an issue with me as i spend most of my time on linux and if you select show tabs and spaces I can see that the spaces are fine.
Just thought you would like to know.
thanks
Get BlueMail <https://bluemail.me> for Desktop
Veronica Berglyd Olsen wrote:
There was a similar issue reported before, and then it was a font issue. In either case, the text editor itself is provided by the Qt library, so and I don't control the rendering of the text itself.
Could you try switching editor font on novelWriter on the Mac?

**Comment by mvdkleijn** [comment] 2023-06-17 10:55
Considering that the OP stated that the problem is only there on Mac and Linux is fine, we can safely assume that the NovelWriter files are fine.

Indeed, like this sounds more like a rendering issue of bug in the Mac version of the QT component.

**Comment by vkbo** [comment] 2023-06-17 11:27
Well, I gave it a test by coying over a project on Linux to the macOS Catalina VM with rsync, and opened it. I could not reproduce the problem. Everything looked fine.

**Comment by saikyun** [comment] 2023-06-20 09:12
I have the same problem. As far as I can tell, it's not about the font, because the space is literally gone. I was thinking that it might be some sort of autocorrect, though I have no clue as to what sort that might be.

**Comment by saikyun** [comment] 2023-06-29 20:16
Oh, I tried changing font, and that solved it for me. I wonder now, the default setting is something like AppleUISystemFont or similar. Maybe that is acting weird in some way?

**Comment by vkbo** [comment] 2023-06-29 20:29
That should be the default for the GUI, but not for the editor. For MacOS it should default to Courier, but if that's not available, it will default to the UI font, yes.

**Comment by saikyun** [comment] 2023-07-07 11:24
I don't have Courier on my machine, but I do have Courier New.

**Comment by vkbo** [comment] 2023-07-07 11:28
That may explain why it falls back to the UI font, yes. I tested the implementation on MacOS Catalina, and had Courier there, so that's what I set as default. A solution here would be to provide a few font options. It's not a problem for novelWriter to iterate through a few to pick one before it falls back to the UI font. Feel free to post suggestions here. They should be generally available on MacOS and be fairly standard. Like whatever Safari, word processors, or whatever, would pick as defaults.

**Comment by vkbo** [comment] 2023-07-19 23:27
I'm changing the default font on MacOS to Helvetica. Can you confirm if changing the font works, @mcrislip? I know you initially said it didn't, but since it worked for others, maybe you've tried some more fonts? Make sure you change the font under Preferences -> Documents, and not the GUI font.

**Comment by mcrislip** [comment] 2023-07-20 18:22
Im away from my mac for a while, but will do it next week and let you 
know.

**Comment by vkbo** [comment] 2023-07-30 11:53
I'm closing this now. We can always reopen it if the issue remains.

**Closed by vkbo** 2023-07-30 11:53 UTC
Labels: bug, dependency, packaging
