### ISSUE TITLE
error. starting application from terminal after sudo ./setup.py xdg-install

### ISSUE THREAD

**Issue by primeid** [vkbo/novelWriter#775] opened 2021-05-06 19:32 UTC
After installing from minimal package using script -> sudo ./setup.py xdg-install

I get this error when starting novelWriter from terminal. Using Ubuntu 20.04.

CRITICAL  AttributeError: 'QTranslator' object has no attribute 'filePath'
  File "/home/magnus/.local/bin/novelWriter", line 8, in <module>
    sys.exit(main())
  File "/home/magnus/.local/lib/python3.8/site-packages/nw/__init__.py", line 284, in main
    CONFIG.initLocalisation(nwApp)
  File "/home/magnus/.local/lib/python3.8/site-packages/nw/config.py", line 394, in initLocalisation
    logger.debug("Loaded: %s" % qTrans.filePath())
WARNING   Could not find main GUI window so cannot open error dialog

**Comment by vkbo** [comment] 2021-05-06 19:34
This is a duplicate of #774 and has already been fixed in the `main` branch. I will make a new release in a bit.

**Closed by vkbo** 2021-05-06 19:34 UTC
Labels: bug, duplicate

**Comment by vkbo** [comment] 2021-05-06 19:40
By the way, the issue can be fixed by upgrading to PyQt5 and Qt 5.15, but I don't want to require that people do that, so the fix that I made will remove that restriction.

**Comment by vkbo** [comment] 2021-05-06 20:35
Done. New release is up. I tested the fix earlier on Ubuntu 18.04, so it should do the trick.
