### ISSUE TITLE
Search-related shortcuts and file edit shortcut don't work in focus mode

### ISSUE THREAD

**Issue by gorhu** [vkbo/novelWriter#716] opened 2021-03-22 08:51 UTC
Hi! Sorry for writing similar issues in short period of time separately. I'm not sure if it's bug or design decision as I see same behavior when I checked earlier releases but search-related shortcuts and file edit shortcut (CTRL+E) don't work in focus mode. There is no warning/error. When I try other shortcuts like F8, F11, CTRL+A, CTRL+B except file-related ones like CTRL+N, CTRL+O (which I think they causes more troubles if they work :) ), they work too. Icons/buttons work as It should be and it's easy to activate/deactivate focus mode or click icons, so it isn't a critical thing for me. Just wanted to point it when I see working search and file edit icons in focus mode but not shortcuts.

**Comment by vkbo** [comment] 2021-03-22 09:20
Hi!

No, thanks a lot for posting issue reports when you find something. Everyone use the application differently, and my habits are different from other people, so I don't always discover issues in features I rarely use myself, like for instance search/replace.

The menu is switched off when you go to Focus Mode. This is deliberate. But the menu actions related to text editing are manually reconnected to the main GUI so that the keyboard shortcuts for the editor still work. Since these are manually added back, there's always a chance that one or two have been forgotten.

You're right that shortcuts related to the project tree are disabled. That is deliberate. Same with `Ctrl+E` which used to be a project tree feature only. However, there is now an edit button in the document header that does the same thing for the current open document. This button doesn't have a shortcut, so therefore the shortcut itself doesn't work in Focus Mode. The same is true for the search functionality as it is now.

However, since the search button is also available from the document header, it makes sense to add the keyboard shortcuts to operate the search tool itself. I can certainly enable those in Focus Mode.

**Comment by vkbo** [comment] 2021-03-22 10:30
**Discovered Bugs**

Just a quick test of the GUI also revealed that the document header buttons are hidden in Focus Mode if you activate it with the maximise button, but not when you activate it from the menu or via shortcut. This is inconsistent, so I will remove the hiding of the buttons entirely. I also noticed that closing the document in Focus Mode would disable the deactivation of Focus Mode itself, leaving you stuck in Focus Mode. The only way to get out is to close the app and open it again. This is a bug.

These are all trivial to fix, and are mostly inconsistencies caused by the same features having multiple ways to activate/deactivate. I'll make a patch tonight for these and I'll probably make a 1.2.2 patch release soon. Too bad I didn't discover these yesterday before the 1.2.1 release!

**Closed** 2021-03-22 18:01 UTC
Labels: bug, enhancement
