### ISSUE TITLE
Build Tool Stay-on-top

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1841] opened 2024-05-01 08:58 UTC
It's possible to edit with an open build tool preview on-screen, but for me there's barely enough display space available while the build tool is stay-on-top. Once open, it's clunky and obtrusive until you close it.

I can't think of a reason why this window is stay-on-top. It's not modal, large enough to be found again easily if you happen to lose it in your desktop clutter, and you can always bring it to front again with F5 or a button click.

If you agree, consider dropping the stay-on-top hint.

**Comment by vkbo** [comment] 2024-05-01 09:08
This is how Qt dialogs behave when the dialog is a child element of the main window. I'm not aware of a setting that prevents this. Perhaps it would be possible to make the dialog not a child of the main window, but I think that causes problems on MacOS.

**Comment by vkbo** [comment] 2024-05-01 09:28
Did a little tinkering, and I can get it to work on Linux. Windows would be easy to test. I have no ways to test if it works on MacOS, but I do know the window manager there is much more fickle. There are several small hacks with non-modal dialogs to make them work properly on MacOS. The main issue there is that they tend to open in the background.

In any case, I would like to clean up the handling of the Manuscript dialog and its child elements, so I can look into it further. The way settings dialogs for the different builds are handled is also a bit clunky.

**Comment by vkbo** [comment] 2024-05-01 13:04
So, while trying to solve this, I rewrote the dialog caching feature for builds, and added a custom garbage collector to clear out old dialogs from memory. This works fine, and is a good replacement for the current implementation that looks through child windows to find out whether a dialog is already open before creating it. This is needed here since the build settings dialogs need to be singular per build, and therefore cached by their build ID.

Anyway, the rewrite allowed me to remove the parent/child relationship between the main window, the manuscript tool, and the build settings dialogs.

However, this returns me to the old problem that on Wayland on Linux, there is no way to raise a dialog from the background. At least not from Qt5. This results in the following common scenario:

* You open the manuscript dialog.
* You click back into the main window to do something, and the manuscript dialog pops into the background.
* You forget that the manuscript dialog is open, but hidden, and try to activate it again.
* Nothing happens, because the dialog is already open, just hidden behind other windows.

This is, as far as I can tell, unsolvable. As I recall, this is also a variant of the problem that arose on MacOS, although the window manager there has slightly different rules. But the effect was the same.

That is why the manuscript dialog is set as a child object of the main window. The downside is that it will always be stacked on top of the main window, no matter what. The latter is less annoying than the former. At least based on user feedback.

So, my conclusion is that this is a stale mate. I can merge my improved cache implementation which will make the dialogs open faster, but otherwise I will have to revisit this issue when I switch to Qt6 to see if it has a better solution. It is certainly better at dealing with Wayland.

**Comment by vkbo** [comment] 2024-05-02 13:35
Update on this is that the solution I implemented works on Windows, but not on Wayland, and I couldn't get it to work on Xorg on a Ubuntu VM either. I don't know about MacOS. As far as I can find out, I don't think there is a solution for Wayland. It doesn't seem like it's something it supports. I suspect it doesn't work on Qt6 either. At least the bug report I found indicates as much. Not really an expert on all the different window managers. What I know is mostly from trial and error. 😄

**Comment by tmarplatt** [comment] 2024-05-13 09:20
What's the use case for keeping the build tool open? Quick manuscript iteration?

**Comment by vkbo** [comment] 2024-06-02 20:43
> What's the use case for keeping the build tool open? Quick manuscript iteration?

Yeah, pretty much. It was designed as non-modal exactly for that kind of use. But it is really hard to get around the OS/desktop window manager.

**Comment by vkbo** [comment] 2024-11-08 21:10
Closing this since this is more or less out of the hands of the application beyond what is always added. This is window manager territory, and even Qt with all its hacks can't provide a consistent experience across platforms.

**Closed by vkbo** 2024-11-08 21:10 UTC
Labels: build tool, usability, investigate
