### ISSUE TITLE
Save a project as a new project template

### ISSUE THREAD

**Issue by anthonyirwin82** [vkbo/novelWriter#1550] opened 2023-10-23 05:32 UTC
When starting a writing project, there are a bunch of things that you do over and over again for story development.

Writing templates with questions for you to answer to help you flesh out your story idea, characters, world, story premise, etc.

You can create folders and notes in Novel Writer for just about anything so you can follow Snowflake method, Save the cat, Story circle or any other method for fleshing out your story.

The problem is you need to manually create the structure and the template questions for you to work through each time you create a new project.

It would be nice if you could do this once and save it as a new project template. This way, as you expand your default writing templates, you can update your new project template and have it for each new writing project automatically.

**Comment by vkbo** [comment] 2023-10-23 06:24
This is a duplicate of #841, so I'm closing it, but it is a "planned feature" so it will be added. Please add feature ideas in the other ticket.

**Closed by vkbo** 2023-10-23 06:24 UTC
Labels: duplicate
