### ISSUE TITLE
Menus open in a weird spot (Linux AppImage, Debian 12)

### ISSUE THREAD

**Issue by EugeneUvin** [vkbo/novelWriter#1536] opened 2023-10-18 06:57 UTC
1. Get AppImage
2. Run it
3. Click a menu - Project or other.
**Expected:** Menu opens in a proper location under the menu bar.
**Actual: see screenshot**
![image](https://github.com/vkbo/novelWriter/assets/9447963/eea213f8-d390-4f55-b6ae-fd69d98635b7)

**Comment by vkbo** [comment] 2023-10-18 07:05
Does it happen every time, or just once in a while?

This is an issue in the Qt framework that I've seen from time to time. The novelWriter code does not position the menus itself, so it's not an issue I can easily fix.

**Comment by vkbo** [comment] 2023-10-18 07:08
I think it's an issue with the desktop environment as well (maybe Wayland-related). I've seen it happen more on Debian 12 than on Debian 11. For the record, I could not reproduce the issue with the AppImage on Debian 12 just now, but as I've said, I've seen it randomly happen form time to time.

**Comment by EugeneUvin** [comment] 2023-10-18 08:34
I forgot to mention I have two monitor configuration. Maybe its the cause combined with Wayland.

**Comment by vkbo** [comment] 2023-10-18 08:35
Yes, that is the root issue, because Qt apparently has issues calculating coordinates on two screens. Especially if there is no 0,0 coordinate on the screen.

**Comment by vkbo** [comment] 2023-10-18 08:48
I honestly don't think I can fix this until I move novelWriter to Qt6, unless they backport a fix to 5.15 in the distros. Qt won't as the community edition reached EOL in May this year.

I've started to prepare the code to move to Qt6, but I doubt I'll make the switch until next year.

**Comment by vkbo** [comment] 2023-10-18 08:51
But one question: Are the menus always in the wrong place, or only occasionally? It only happens to me sometimes.

**Comment by EugeneUvin** [comment] 2023-10-18 09:07
I am only starting using it and the menus are always displaced - on my main laptop monitor or in my second monitor on this video.
[vokoscreenNG-2023-10-18_12-06-49.webm](https://github.com/vkbo/novelWriter/assets/9447963/8f864353-0dba-4aba-abaa-963b5eb6c3ab)

**Comment by EugeneUvin** [comment] 2023-10-18 09:14
Yes, aligning top of monitors worked. Now, the menu is in a correct place.

**Comment by vkbo** [comment] 2023-10-18 09:21
Ok, good to know. Then we have a solution, and I have a way to test the issue as I can just misalign my screens to reproduce it. I'll see if the parent widget suggestion from one of the bug reports will help. If not, the issue will remain unsolved until I move to Qt 6 in a few months. As far as I can tell, the underlying bug is fixed in Qt 6.5.

**Closed** 2023-11-04 16:31 UTC
Labels: bug, user interface, qt issue
